source "http://rubygems.org"

gem "sinatra", "1.1.0"
gem "sinatra-content-for"
gem "activerecord"
gem "sinatra-activerecord"
gem "httparty"
gem "log4r", "~> 1.1.9"
gem "mysql"
gem "sqlite3-ruby"
gem "dalli"
gem "haml"
gem "sass"
gem "rest-open-uri"
